### ISSUE TITLE
Changes in Authorities validation

### ISSUE THREAD

**Issue by JoelleSciboz** [dag-hammarskjold-library/dlx-rest#1510] opened 2024-08-09 14:04 UTC
New field: 043
Updated field: 110 - valid values in $9
Updated field: 046 - required subfield, valid subfields, valid values - date.

See the details in the attached file.

[auth_validation_changes_2024_08_08.txt](https://github.com/user-attachments/files/16562245/auth_validation_changes_2024_08_08.txt)

**Comment by viola-v** [comment] 2024-08-29 15:04
Reopening because 043 was supposed to have 
            "validSubfields": ["b", "c"],
            "defaultSubfields": ["b", "c"]
But no default subfields appear, and there is no validation:
<img width="156" alt="image" src="https://github.com/user-attachments/assets/4d7d7fa9-82c6-4c8b-a99c-70e2cf3dbe2d">

Same for 046, I don't see any of this implemented: 
"requiredSubfields": ["s"],
            "validSubfields": ["s","t"],
            "defaultSubfields": ["s"],
            "isDate": {
                "s": true,
                "t": true
            },
            "validRegex": {
                "s": ["^\\d{4}-?\\d{2}-?\\d{2}$"],
                "t": ["^\\d{4}-?\\d{2}-?\\d{2}$"]

It looks like only the changes for 110 were made?

**Comment by viola-v** [comment] 2024-09-03 18:37
Closing, works as intended!

**Closed by viola-v** 2024-09-03 18:37 UTC
Labels: function: validation, type: configuration, iamu_2024
