### ISSUE TITLE
Use enter key to run advanced search

### ISSUE THREAD

**Issue by viola-v** [dag-hammarskjold-library/dlx-rest#842] opened 2022-12-06 19:16 UTC
In the Bib "advanced Search", can the "Enter" key function as "Search" instead of having to click the "search" icon with the mouse?  In the "simple search" option, "Enter" key works as "search".

**Comment by jbukhari** [comment] 2022-12-06 22:10
duplicate of #644

**Closed** 2022-12-13 21:21 UTC
Labels: user feedback, to analyze
